### ISSUE TITLE
how to evaluate the RMSD?

### ISSUE THREAD

**Issue by pengzhangzhi** [Graylab/IgFold#10]
There are multiple ways to calculate RMSD, Would you like to share how you calculate the RMSD, is it KabschRMSD or something else? In addition, how do you do the RMSD evaluation on CDR region?  We are trying to follow your work~ Please share more information to us so that we can have a fair comparison. Thank you.

Best,
Zhangzhi

**Comment by jeffreyruffolo** [comment]
Hello, for evaluation on the benchmark we use the built-in evaluation function within RosettaAntibody. This function aligns on a set of highly conserved residues within the framework regions. We have a wrapper for this function here:
https://github.com/Graylab/IgFold/blob/b96846b6c8e175da1acd2d68e10098277e840ce5/igfold/utils/ab_metrics.py#L22

During training, we align only on the residues with beta sheet structures and calculate an RMSD that way. This gives a quick approximation of the metric above for error estimation, though it is not identical.

**Comment by pengzhangzhi** [comment]
thanks! I think nanobody is the same? The rosettaantibody has inferface for nanobody, right?

**Comment by pengzhangzhi** [comment]
Hi. Another question, from the code, I conjecture that you only test the backbone rmsd without considering the side chains?
```python
results = pyrosetta.rosetta.protocols.antibody.cdr_backbone_rmsds(
        pose_1,
        pose_2,
        pose_i1,
        pose_i2,
    )
```
I think the reason is that the side chains are reconstructed by rosetta?

**Comment by jeffreyruffolo** [comment]
Yes, we only evaluate RMSD for backbone heavy atoms. The evaluation is the same for paired Fvs / nanobodies. We use the same wrapper for every structure we compare.

**Comment by jeffreyruffolo** [comment]
Closing this issue but please reopen if there's anything else unclear.

**Comment by pengzhangzhi** [comment]
Thanks! Do you calculate Backbone RMSD on atoms C,CA, N?
