### ISSUE TITLE
Is there a sequence limit for structure prediction?

### ISSUE THREAD

**Issue by bernym12** [Graylab/IgFold#13]
Upon running the folding algorithm, I've noticed a few of my targets fail due to an error such as the following:

`RuntimeError: The expanded size of the tensor (587) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [1, 587].  Tensor sizes: [1, 512] `

which gives the impression that there is either a sequence limit or an error in how the input is processed. So I was just wondering which of these is true?

**Comment by bernym12** [comment]
Found it's limited to 512 from another open issue

**Comment by jeffreyruffolo** [comment]
Hello, yes the AntiBERTy model is limited to 512 residues. In practice this shouldn't ever be a limitation as the model is only trained on variable fragment chains which are closer to 100-130 residues. Although there are some variable fragments with long CDR loops, I wouldn't expect the overall sequence length to approach 512 residues (if it does the Fv probably isn't being truncated for input).
