### ISSUE TITLE
how to get pre-trained weight

### ISSUE THREAD

**Issue by maxshen29** [Graylab/IgFold#16]
i try to run igfold , there is no response at this step：

Downloading checkpoint files...

Is there anywhere else to download the pre-trained weights？

**Comment by jeffreyruffolo** [comment]
Hello, the pretrained checkpoints can be downloaded directly from here: `https://data.graylab.jhu.edu/IgFold.tar.gz`. After unzipping, the checkpoint paths can be provided directly to `IgFoldRunner` like this:
```python
model_ckpts = ["/path/to/model1.ckpt", "/path/to/model2.ckpt", ...]
igfold = IgFoldRunner(model_ckpts= model_ckpts)
```

**Comment by maxshen29** [comment]
thanks for your help
