### ISSUE TITLE
traning problem 

### ISSUE THREAD

**Issue by maxshen29** [Graylab/IgFold#17]
**i use the sample ：**

from igfold import IgFoldRunner
sequences = {
    "H": "QVQLQESGGGLVQAGGSLTLSCAVSGLTFSNYAMGWFRQAPGKEREFVAAITWDGGNTYYTDSVKGRFTISRDNAKNTVFLQMNSLKPEDTAVYYCAAKLLGSSRYELALAGYDYWGQGTQVTVS"
}
pred_pdb = "my_nanobody.pdb"

igfold = IgFoldRunner()
igfold.fold(
    pred_pdb, # Output PDB file
    sequences=sequences, # Nanobody sequence
    do_refine=False, # Refine the antibody structure with PyRosetta
    do_renum=True, # Renumber predicted antibody structure (Chothia)
)

**get the erro：**
Warning: AbNumber not available. Provide --use_abnum to renumber with the AbNum server.
cannot import name 'clean_pdb' from 'igfold.utils.pdb' (/data/miniconda3/envs/igfold/lib/python3.9/site-packages/igfold/utils/pdb.py)
Completed folding in 0.90 seconds.

**How to solve it？**

**Comment by jeffreyruffolo** [comment]
Hello, I recently replaced ANARCI with AbNumber for renumbering structures. You may need to install this tool specifically, here's the conda command: 
```bash
$ conda install -c bioconda abnumber
```
Altnernatively, you can pass the `use_abnum=True` argument to the `igfold.fold` command, which will send your structure to a server for renumbering.

**Comment by kimdn** [comment]
Both my python3.8 and 3.9 condas cannot install abnumber as
<img width="767" alt="Screen Shot 2023-02-26 at 12 55 08 AM" src="https://user-images.githubusercontent.com/3903446/221401228-e5abc9d2-18b5-426a-8ff7-cd097c0ddc71.png">


Maybe I just need to use

```
igfold.fold(
pred_pdb, # Output PDB file
sequences=sequences, # Nanobody sequence
do_refine=False, # Refine the antibody structure with PyRosetta
do_renum=True, # Renumber predicted antibody structure (Chothia)
use_abnum=True,
)

```
