### ISSUE TITLE
Runtime error on Google colab

### ISSUE THREAD

**Issue by iamabhik** [Graylab/IgFold#18]
Hello,

I am trying to run IgFold on Google Colab. It shows problem in running "Load IgFold models", seems module import issues with the following error message

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[/usr/local/lib/python3.7/site-packages/transformers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
   1092         try:
-> 1093             return importlib.import_module("." + module_name, self.__name__)
   1094         except Exception as e:

27 frames
ModuleNotFoundError: No module named 'tokenizers.tokenizers'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.7/site-packages/transformers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
   1093             return importlib.import_module("." + module_name, self.__name__)
   1094         except Exception as e:
-> 1095             raise RuntimeError(
   1096                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
   1097                 f" traceback):\n{e}"

RuntimeError: Failed to import transformers.models.auto.tokenization_auto because of the following error (look up to see its traceback):
No module named 'tokenizers.tokenizers'

I searched on google but no clear help is indicated. Please suggest, Thank you

**Comment by jeffreyruffolo** [comment]
Hello, this may be a result of Colab updating to python3.8 in the last couple days. I am working on a fix for this currently.
