### ISSUE TITLE
About nanobody data

### ISSUE THREAD

**Issue by YiningWang2** [Graylab/IgFold#19]
Hello, recently, i use your nanobody test data to test the model performance on NanoBody. However, I want to get more data. So is there any way to identify if a structure is  nanobody or how to get nanobody data from RCSB PDB? Thanks so much.

**Comment by jeffreyruffolo** [comment]
Hello, you can use the [SAbDab website](http://opig.stats.ox.ac.uk/webapps/newsabdab/sabdab/search/) to do searches like this. On this page, there is an option for "Antibody type" that you can set to "VHH," which should give you all of the nanobodies from PDB.

**Comment by YiningWang2** [comment]
Wow! Thanks so much for your helpful reply. And Is there any tool to identify a nanobody by protein sequence?
