### ISSUE TITLE
Contact information for commercial use

### ISSUE THREAD

**Issue by zeroaltitude** [Graylab/IgFold#20]
Hi all, had no other way to try to reach out than making a github issue. It is awesome that you have a license. It specifies that a company that wants to use this software for commercial use would need a separate written license. Great! Unfortunately, it doesn't say whom to reach out to in order to get that done. So this issue can simultaneously be considered a request to add that information to this repo, and also, a request for the information itself as I represent such a company! Thank you so much in advance, this software is awesome!

**Comment by jeffreyruffolo** [comment]
Hello! Thank you for your interest, you can contact the Johns Hopkins Tech Transfer office at [dmalon11@jhu.edu](mailto:dmalon11@jhu.edu) and they should be able to help with a license.
