### ISSUE TITLE
python version mismatch

### ISSUE THREAD

**Issue by XiaoTigerHAO** [Graylab/IgFold#22]
Hi developer,

Greetings!

Here I report two issues in running the IgFold in a conda virtual env with python 3.8.0.

1. Python version mismatch: module was compiled for Python 3.5, but the interpreter version is incompatible: 3.8.0 (default, Nov  6 2019, 21:49:08)
I got this information in importing the igfold module. which version of the python is recommended?

2. RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
Try to ignore the issue 1, and run the following steps listed in the website, I got this error. The program cannot be run anymore.

Please help to check that if any solution could be useful in solving those problems.

Thanks very much!

Best
User
Jan 12, 2023

**Comment by jeffreyruffolo** [comment]
Hello, sorry for the delay in responding to your issue. I've made a few changes to the dependencies and am able to run in python 3.8 with these updates. Can you please try again?
