### ISSUE TITLE
No igfold_4.ckpt ?

### ISSUE THREAD

**Issue by shubihu** [Graylab/IgFold#23]
I downloaded the model weight, but there is no igfold_4.ckpt ?  
The link is https://data.graylab.jhu.edu/IgFold.tar.gz

**Comment by jeffreyruffolo** [comment]
@shubihu, this is expected you should only have four models in the download (1, 2, 3, and 5). The numbers correspond to the random seeds used during training. The training run beginning with seed 4 was unstable, so we used 5 instead to get an ensemble of four models.

**Comment by shubihu** [comment]
> How do you install IgFold ? I keep having trouble installing it on my computer.
Just via pip like this
<img width="859" alt="image" src="https://user-images.githubusercontent.com/36021958/216524073-ea3874e8-715b-4dfb-b447-cedf95a0c776.png">

**Comment by shubihu** [comment]
> @shubihu, this is expected you should only have four models in the download (1, 2, 3, and 5). The numbers correspond to the random seeds used during training. The training run beginning with seed 4 was unstable, so we used 5 instead to get an ensemble of four models.

OK, thanks.
