### ISSUE TITLE
pytorch3d version missing 

### ISSUE THREAD

**Issue by dannykwells-sab** [Graylab/IgFold#25]
Hi @jeffreyruffolo  - As I think a few others have noted, the version is missing for pytorch3d, which is causing an error in conda when we try to install:

```
ERROR: Could not find a version that satisfies the requirement pytorch3d (from igfold) (from versions: none)
ERROR: No matching distribution found for pytorch3d
```
Is there a preferred version of pytorch3d that you have tested works for igfold?

**Comment by jeffreyruffolo** [comment]
Hello, I've now removed `pytorch3d` from the dependencies to resolve these issues. Only a couple functions were used, so it was easy to internalize them.

Please let me know if you still have problems installing.
