### ISSUE TITLE
Error in Colab Notebook: `GLIBCXX_3.4.29' not found 

### ISSUE THREAD

**Issue by ajasja** [Graylab/IgFold#27]
Hi,

The default notebook does not run:
(I just used Run all with all default options).

Here is link to a copy of the notebook:
https://colab.research.google.com/drive/11bH_aFT2Wm_0r3UQk4JNFTbsa3hJcXEb?usp=sharing

![image](https://user-images.githubusercontent.com/19926/221139684-b67dcddf-50c1-49d6-8ec0-1adf61c00e0e.png)

```Warning: PyRosetta not found, OpenMM will be used instead.
No module named 'pyrosetta'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-3-2d0e067d8df6>](https://localhost:8080/#) in <module>
      4     sys.path.insert(0, f"/usr/local/lib/python{python_version}/site-packages/")
      5 
----> 6 from igfold.utils.visualize import *
      7 from igfold import IgFoldRunner
      8 

12 frames
[/usr/local/lib/python3.8/site-packages/pandas/core/window/ewm.py](https://localhost:8080/#) in <module>
     13 
     14 from pandas._libs.tslibs import Timedelta
---> 15 import pandas._libs.window.aggregations as window_aggregations
     16 from pandas._typing import (
     17     Axis,

ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/lib/python3.8/site-packages/pandas/_libs/window/aggregations.cpython-38-x86_64-linux-gnu.so)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by kimdn** [comment]
I experienced the same error today.

**Comment by jeffreyruffolo** [comment]
Hi, thanks for pointing this out. I’m currently trying to work through some issues adapting IgFold to the updated environment on Colab. Hopefully will have this fixed soon!

**Comment by Wei-Lan** [comment]
I experienced the same error today. +1

**Comment by ramosemi** [comment]
same here! has anyone been able to run the default sequence? How to install GLIBCXX?

**Comment by JPereira-FJB** [comment]
I experienced the same error today. Any fix?

**Comment by ramosemi** [comment]
I couldn't find a fix for Collab but ended up using Cosmic2 server which hosts IgFold: https://cosmic2.sdsc.edu:8443/gateway/tools.action

I generated models of an scFv and a VHH/nanobody we have been using for pre-clinical CAR T cell development.

Curiously, IgFold and the Antibody Grafting app on the Rosie2 server omits a key amino acid from CDR3 in my antibody (F is deleted entirely), there is a second deletion in the light chain too.  Is there a reason for this? Any resources I could read more?

Thank you IgFold team, really incredible work!

Emilio
________________________________

**Comment by jeffreyruffolo** [comment]
Hello all, sorry for the delays on getting this fixed. Colab has been updating the base environment fairly often over the last several months and it has been difficult to keep the notebook up to date. I hope to have this fixed soon to work on the current version of Colab.

**Comment by JPereira-FJB** [comment]
> I couldn't find a fix for Collab but ended up using Cosmic2 server which hosts IgFold: https://cosmic2.sdsc.edu:8443/gateway/tools.action>

This is a university server, right? Is it open to the public for testing, or something?

**Comment by ramosemi** [comment]
https://cosmic-cryoem.org/tools/igfold/
You should be able to run from Cosmic

________________________________

**Comment by wwl5600** [comment]
the same error today. Any fix?

**Comment by jeffreyruffolo** [comment]
This should be fixed now!

**Comment by ajasja** [comment]
Thanks!

**Comment by JPereira-FJB** [comment]
> This should be fixed now!

I now run into a different error (`No module named 'igfold'`, even though IgFold seems to be properly installed with no warnings or errors in the previous step).
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-2d0e067d8df6>](https://localhost:8080/#) in <cell line: 6>()
      4     sys.path.insert(0, f"/usr/local/lib/python{python_version}/site-packages/")
      5 
----> 6 from igfold.utils.visualize import *
      7 from igfold import IgFoldRunner
      8 

ModuleNotFoundError: No module named 'igfold'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by ajasja** [comment]
Yes, I get the same. Did not have time to dig in yet, but it's probably worth opening a new issue. @JPereira-FJB @jeffreyruffolo 
`pip install igfold` seem to fail for some reason?
