### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by linuxonly801** [Graylab/IgFold#31]
The error occurs when I tried to run the code, please help to fix. THX.

data/personal/yankai/packages/anaconda3/envs/igfold/lib/python3.7/site-packages/Bio/pairwise2.py:283: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  BiopythonDeprecationWarning,

    The code, data, and weights for this work are made available for non-commercial use 
    (including at commercial entities) under the terms of the JHU Academic Software License 
    Agreement. For commercial inquiries, please contact dmalon11[at]jhu.edu.
    License: https://github.com/Graylab/IgFold/blob/main/LICENSE.md
    
Loading 4 IgFold models...
Using device: cuda:0
Successfully loaded 4 IgFold models.
Loaded AntiBERTy model.
length of self.models: <class 'list'> 0
Traceback (most recent call last):
  File "igbody_test.py", line 15, in <module>
    do_renum=True, # Renumber predicted antibody structure (Chothia)
  File "/data/personal/yankai/LiuChang/IgFold/igfold/IgFoldRunner.py", line 120, in fold
    truncate_sequences=truncate_sequences,
  File "/data/personal/yankai/LiuChang/IgFold/igfold/utils/folding.py", line 210, in fold
    best_model_i = scores.index(min(scores))
ValueError: min() arg is an empty sequence

**Comment by jeffreyruffolo** [comment]
Hello, can you please share a set of inputs that I can use to reproduce this behavior?

**Comment by annmary-acog** [comment]
Hi, Im also facing the same issue. Could you please explain how you solved it in a little more detail?

**Comment by yilia-yao** [comment]
Hi, I am also confused. How it comes by pip install? Thanks a lot!
