### ISSUE TITLE
Fail to download Pretrained Weights

### ISSUE THREAD

**Issue by linuxonly801** [Graylab/IgFold#32]
according to the usage:

Note: The first time IgFoldRunner is initialized, it will download the pre-trained weights. This may take a few minutes and will require a network connection.

The first time to run IgFold, it should download the pretrained Weights. But in my machine, it doesn't. So, how to fix this problem? Are there a ftp to download?

**Comment by jeffreyruffolo** [comment]
Hello, can you let me know what version of IgFold you have installed? The download is no longer required in version 0.3.1 if you want to update.

**Comment by linuxonly801** [comment]
when I download the zip file from github, its not working, but with pip install, it works! thanks for the reply.
