### ISSUE TITLE
atom serial number duplicates after the TER record in output PDB

### ISSUE THREAD

**Issue by px172** [Graylab/IgFold#37]
Here is  a part of the PDB file from an example from the demo code:

ATOM    598  C   SER H 122     -13.308  -3.541  25.995  1.00  0.72           C
ATOM    599  CB  SER H 122     -13.603  -2.584  25.501  1.00  0.72           C
ATOM    600  O   SER H 122     -13.651  -3.377  27.165  1.00  0.72           O
TER     601      SER H 122
ATOM    601  N   ASP L 123      12.888   2.582   8.954  1.00  0.62           N
ATOM    602  CA  ASP L 123      11.859   1.989   8.092  1.00  0.62           C
ATOM    603  C   ASP L 123      11.877   3.321   7.378  1.00  0.62           C

The TER record and the next ATOM record have the atom serial number (601).

do_refined and do_renum are set to False.

**Comment by jeffreyruffolo** [comment]
This should be fixed now with an update to the PDB writing functionality.
