### ISSUE TITLE
Execution environment Issues

### ISSUE THREAD

**Issue by Licko0909** [Graylab/IgFold#5]
Hello! I am very interested in your project, and I want to try to predict the antibody structure( PDB:1IGT) by using your model, but THERE are some problems in the process.

I have successfully installed the environment according to your _**requirement.txt**_, but I cannot use it. The error message is as follows:
![Image](https://user-images.githubusercontent.com/27897166/169945451-97e0ba81-a334-4940-ac22-2c62fe977098.png)

I find there( _**requirement.txt**_) are no requirements for CUDA and Python versions.

Here is a list of my environments

```
# packages in environment at /home/LChuang/anaconda3/envs/igfold2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
absl-py                   1.0.0                    pypi_0    pypi
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
antiberty                 0.0.5                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd3eb1b0_0    defaults
argon2-cffi-bindings      21.2.0           py38h7f8727e_0    defaults
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
async-timeout             4.0.2                    pypi_0    pypi
attrs                     21.4.0             pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
beautifulsoup4            4.11.1           py38h06a4308_0    defaults
biopython                 1.79                     pypi_0    pypi
bleach                    4.1.0              pyhd3eb1b0_0    defaults
ca-certificates           2022.4.26            h06a4308_0    defaults
cachetools                5.1.0                    pypi_0    pypi
certifi                   2022.5.18.1      py38h06a4308_0    defaults
cffi                      1.15.0           py38hd667e15_1    defaults
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.5.1            py38h295c915_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
einops                    0.3.0                    pypi_0    pypi
entrypoints               0.4              py38h06a4308_0    defaults
executing                 0.8.3              pyhd3eb1b0_0    defaults
filelock                  3.7.0                    pypi_0    pypi
frozenlist                1.3.0                    pypi_0    pypi
fsspec                    2022.3.0                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.5.post20220512          pypi_0    pypi
ghost-py                  0.2.3                    pypi_0    pypi
google-auth               2.6.6                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.46.1                   pypi_0    pypi
huggingface-hub           0.6.0                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
igfold                    0.0.8                    pypi_0    pypi
importlib-metadata        4.11.3                   pypi_0    pypi
importlib_resources       5.2.0              pyhd3eb1b0_1    defaults
invariant-point-attention 0.1.4                    pypi_0    pypi
iopath                    0.1.9                    pypi_0    pypi
ipykernel                 6.9.1            py38h06a4308_0    defaults
ipython                   8.3.0            py38h06a4308_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
jedi                      0.18.1           py38h06a4308_1    defaults
jinja2                    3.0.3              pyhd3eb1b0_0    defaults
joblib                    1.1.0                    pypi_0    pypi
jsonschema                4.4.0            py38h06a4308_0    defaults
jupyter_client            7.2.2            py38h06a4308_0    defaults
jupyter_core              4.10.0           py38h06a4308_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
kiwisolver                1.4.2                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 11.2.0               h1234567_0    defaults
libgomp                   11.2.0               h1234567_0    defaults
libsodium                 1.0.18               h7b6447c_0    defaults
libstdcxx-ng              11.2.0               h1234567_0    defaults
markdown                  3.3.7                    pypi_0    pypi
markupsafe                2.0.1            py38h27cfd23_0    defaults
matplotlib                3.4.3                    pypi_0    pypi
matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
mistune                   0.8.4           py38h7b6447c_1000    defaults
multidict                 6.0.2                    pypi_0    pypi
nb_conda                  2.2.1            py38h06a4308_1    defaults
nb_conda_kernels          2.3.1            py38h06a4308_0    defaults
nbbrowserpdf              0.2.0                    pypi_0    pypi
nbclient                  0.5.13           py38h06a4308_0    defaults
nbconvert                 6.4.4            py38h06a4308_0    defaults
nbformat                  5.3.0            py38h06a4308_0    defaults
ncurses                   6.3                  h7f8727e_2    defaults
nest-asyncio              1.5.5            py38h06a4308_0    defaults
notebook                  6.4.11           py38h06a4308_0    defaults
numpy                     1.21.2                   pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
openssl                   1.1.1o               h7f8727e_0    defaults
packaging                 21.3               pyhd3eb1b0_0    defaults
pandas                    1.4.2                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0    defaults
parso                     0.8.3              pyhd3eb1b0_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    9.1.1                    pypi_0    pypi
pip                       21.2.4           py38h06a4308_0    defaults
portalocker               2.4.0                    pypi_0    pypi
prometheus_client         0.13.1             pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.20             pyhd3eb1b0_0    defaults
protobuf                  3.20.1                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
py3dmol                   1.8.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    defaults
pydeprecate               0.3.1                    pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0    defaults
pyparsing                 3.0.9                    pypi_0    pypi
pypdf2                    1.27.12                  pypi_0    pypi
pyrosetta                 2022.6+release.28566d4          pypi_0    pypi
pyrsistent                0.18.0           py38heee7806_0    defaults
python                    3.8.13               h12debd9_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-fastjsonschema     2.15.1             pyhd3eb1b0_0    defaults
pytorch-lightning         1.5.10                   pypi_0    pypi
pytorch-ranger            0.1.1                    pypi_0    pypi
pytorch3d                 0.3.0                    pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0           py38h295c915_2    defaults
readline                  8.1.2                h7f8727e_1    defaults
regex                     2022.4.24                pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
sacremoses                0.0.53                   pypi_0    pypi
scipy                     1.8.1                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1    defaults
setuptools                59.5.0                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 2.3.1              pyhd3eb1b0_0    defaults
sqlite                    3.38.3               hc218d9a_0    defaults
stack_data                0.2.0              pyhd3eb1b0_0    defaults
tabulate                  0.8.9                    pypi_0    pypi
tensorboard               2.9.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.13.1           py38h06a4308_0    defaults
testpath                  0.5.0              pyhd3eb1b0_0    defaults
tk                        8.6.11               h1ccaba5_1    defaults
tokenizers                0.11.6                   pypi_0    pypi
torch                     1.7.1                    pypi_0    pypi
torch-optimizer           0.3.0                    pypi_0    pypi
torchmetrics              0.8.2                    pypi_0    pypi
torchvision               0.8.2                    pypi_0    pypi
tornado                   6.1              py38h27cfd23_0    defaults
tqdm                      4.62.1                   pypi_0    pypi
traitlets                 5.1.1              pyhd3eb1b0_0    defaults
transformers              4.18.0                   pypi_0    pypi
typing-extensions         4.2.0                    pypi_0    pypi
typing_extensions         4.1.1              pyh06a4308_0    defaults
urllib3                   1.26.9                   pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1                    py38_1    defaults
werkzeug                  2.1.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7f8727e_1    defaults
yacs                      0.1.8                    pypi_0    pypi
yapf                      0.31.0                   pypi_0    pypi
yarl                      1.7.2                    pypi_0    pypi
zeromq                    4.3.4                h2531618_0    defaults
zipp                      3.8.0            py38h06a4308_0    defaults
zlib                      1.2.12               h7f8727e_2    defaults
```

**Comment by Licko0909** [comment]
> Hello! I am very interested in your project, and I want to try to predict the antibody structure( PDB:1IGT) by using your model, but THERE are some problems in the process.
> 
> I have successfully installed the environment according to your _**requirement.txt**_, but I cannot use it. The error message is as follows: ![Image](https://user-images.githubusercontent.com/27897166/169945451-97e0ba81-a334-4940-ac22-2c62fe977098.png)
> 
> I find there( _**requirement.txt**_) are no requirements for CUDA and Python versions.
> 
> Here is a list of my environments
> 
> ```
> # packages in environment at /home/LChuang/anaconda3/envs/igfold2:
> #
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main    defaults
> _openmp_mutex             5.1                       1_gnu    defaults
> absl-py                   1.0.0                    pypi_0    pypi
> aiohttp                   3.8.1                    pypi_0    pypi
> aiosignal                 1.2.0                    pypi_0    pypi
> antiberty                 0.0.5                    pypi_0    pypi
> argon2-cffi               21.3.0             pyhd3eb1b0_0    defaults
> argon2-cffi-bindings      21.2.0           py38h7f8727e_0    defaults
> asttokens                 2.0.5              pyhd3eb1b0_0    defaults
> async-timeout             4.0.2                    pypi_0    pypi
> attrs                     21.4.0             pyhd3eb1b0_0    defaults
> backcall                  0.2.0              pyhd3eb1b0_0    defaults
> beautifulsoup4            4.11.1           py38h06a4308_0    defaults
> biopython                 1.79                     pypi_0    pypi
> bleach                    4.1.0              pyhd3eb1b0_0    defaults
> ca-certificates           2022.4.26            h06a4308_0    defaults
> cachetools                5.1.0                    pypi_0    pypi
> certifi                   2022.5.18.1      py38h06a4308_0    defaults
> cffi                      1.15.0           py38hd667e15_1    defaults
> charset-normalizer        2.0.12                   pypi_0    pypi
> click                     8.1.3                    pypi_0    pypi
> cycler                    0.11.0                   pypi_0    pypi
> debugpy                   1.5.1            py38h295c915_0    defaults
> decorator                 5.1.1              pyhd3eb1b0_0    defaults
> defusedxml                0.7.1              pyhd3eb1b0_0    defaults
> einops                    0.3.0                    pypi_0    pypi
> entrypoints               0.4              py38h06a4308_0    defaults
> executing                 0.8.3              pyhd3eb1b0_0    defaults
> filelock                  3.7.0                    pypi_0    pypi
> frozenlist                1.3.0                    pypi_0    pypi
> fsspec                    2022.3.0                 pypi_0    pypi
> future                    0.18.2                   pypi_0    pypi
> fvcore                    0.1.5.post20220512          pypi_0    pypi
> ghost-py                  0.2.3                    pypi_0    pypi
> google-auth               2.6.6                    pypi_0    pypi
> google-auth-oauthlib      0.4.6                    pypi_0    pypi
> grpcio                    1.46.1                   pypi_0    pypi
> huggingface-hub           0.6.0                    pypi_0    pypi
> idna                      3.3                      pypi_0    pypi
> igfold                    0.0.8                    pypi_0    pypi
> importlib-metadata        4.11.3                   pypi_0    pypi
> importlib_resources       5.2.0              pyhd3eb1b0_1    defaults
> invariant-point-attention 0.1.4                    pypi_0    pypi
> iopath                    0.1.9                    pypi_0    pypi
> ipykernel                 6.9.1            py38h06a4308_0    defaults
> ipython                   8.3.0            py38h06a4308_0    defaults
> ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
> jedi                      0.18.1           py38h06a4308_1    defaults
> jinja2                    3.0.3              pyhd3eb1b0_0    defaults
> joblib                    1.1.0                    pypi_0    pypi
> jsonschema                4.4.0            py38h06a4308_0    defaults
> jupyter_client            7.2.2            py38h06a4308_0    defaults
> jupyter_core              4.10.0           py38h06a4308_0    defaults
> jupyterlab_pygments       0.1.2                      py_0    defaults
> kiwisolver                1.4.2                    pypi_0    pypi
> ld_impl_linux-64          2.38                 h1181459_1    defaults
> libffi                    3.3                  he6710b0_2    defaults
> libgcc-ng                 11.2.0               h1234567_0    defaults
> libgomp                   11.2.0               h1234567_0    defaults
> libsodium                 1.0.18               h7b6447c_0    defaults
> libstdcxx-ng              11.2.0               h1234567_0    defaults
> markdown                  3.3.7                    pypi_0    pypi
> markupsafe                2.0.1            py38h27cfd23_0    defaults
> matplotlib                3.4.3                    pypi_0    pypi
> matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
> mistune                   0.8.4           py38h7b6447c_1000    defaults
> multidict                 6.0.2                    pypi_0    pypi
> nb_conda                  2.2.1            py38h06a4308_1    defaults
> nb_conda_kernels          2.3.1            py38h06a4308_0    defaults
> nbbrowserpdf              0.2.0                    pypi_0    pypi
> nbclient                  0.5.13           py38h06a4308_0    defaults
> nbconvert                 6.4.4            py38h06a4308_0    defaults
> nbformat                  5.3.0            py38h06a4308_0    defaults
> ncurses                   6.3                  h7f8727e_2    defaults
> nest-asyncio              1.5.5            py38h06a4308_0    defaults
> notebook                  6.4.11           py38h06a4308_0    defaults
> numpy                     1.21.2                   pypi_0    pypi
> oauthlib                  3.2.0                    pypi_0    pypi
> openssl                   1.1.1o               h7f8727e_0    defaults
> packaging                 21.3               pyhd3eb1b0_0    defaults
> pandas                    1.4.2                    pypi_0    pypi
> pandocfilters             1.5.0              pyhd3eb1b0_0    defaults
> parso                     0.8.3              pyhd3eb1b0_0    defaults
> pexpect                   4.8.0              pyhd3eb1b0_3    defaults
> pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
> pillow                    9.1.1                    pypi_0    pypi
> pip                       21.2.4           py38h06a4308_0    defaults
> portalocker               2.4.0                    pypi_0    pypi
> prometheus_client         0.13.1             pyhd3eb1b0_0    defaults
> prompt-toolkit            3.0.20             pyhd3eb1b0_0    defaults
> protobuf                  3.20.1                   pypi_0    pypi
> ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
> pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
> py3dmol                   1.8.0                    pypi_0    pypi
> pyasn1                    0.4.8                    pypi_0    pypi
> pyasn1-modules            0.2.8                    pypi_0    pypi
> pycparser                 2.21               pyhd3eb1b0_0    defaults
> pydeprecate               0.3.1                    pypi_0    pypi
> pygments                  2.11.2             pyhd3eb1b0_0    defaults
> pyparsing                 3.0.9                    pypi_0    pypi
> pypdf2                    1.27.12                  pypi_0    pypi
> pyrosetta                 2022.6+release.28566d4          pypi_0    pypi
> pyrsistent                0.18.0           py38heee7806_0    defaults
> python                    3.8.13               h12debd9_0    defaults
> python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
> python-fastjsonschema     2.15.1             pyhd3eb1b0_0    defaults
> pytorch-lightning         1.5.10                   pypi_0    pypi
> pytorch-ranger            0.1.1                    pypi_0    pypi
> pytorch3d                 0.3.0                    pypi_0    pypi
> pytz                      2022.1                   pypi_0    pypi
> pyyaml                    6.0                      pypi_0    pypi
> pyzmq                     22.3.0           py38h295c915_2    defaults
> readline                  8.1.2                h7f8727e_1    defaults
> regex                     2022.4.24                pypi_0    pypi
> requests                  2.26.0                   pypi_0    pypi
> requests-oauthlib         1.3.1                    pypi_0    pypi
> rsa                       4.8                      pypi_0    pypi
> sacremoses                0.0.53                   pypi_0    pypi
> scipy                     1.8.1                    pypi_0    pypi
> seaborn                   0.11.2                   pypi_0    pypi
> send2trash                1.8.0              pyhd3eb1b0_1    defaults
> setuptools                59.5.0                   pypi_0    pypi
> six                       1.16.0             pyhd3eb1b0_1    defaults
> soupsieve                 2.3.1              pyhd3eb1b0_0    defaults
> sqlite                    3.38.3               hc218d9a_0    defaults
> stack_data                0.2.0              pyhd3eb1b0_0    defaults
> tabulate                  0.8.9                    pypi_0    pypi
> tensorboard               2.9.0                    pypi_0    pypi
> tensorboard-data-server   0.6.1                    pypi_0    pypi
> tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
> termcolor                 1.1.0                    pypi_0    pypi
> terminado                 0.13.1           py38h06a4308_0    defaults
> testpath                  0.5.0              pyhd3eb1b0_0    defaults
> tk                        8.6.11               h1ccaba5_1    defaults
> tokenizers                0.11.6                   pypi_0    pypi
> torch                     1.7.1                    pypi_0    pypi
> torch-optimizer           0.3.0                    pypi_0    pypi
> torchmetrics              0.8.2                    pypi_0    pypi
> torchvision               0.8.2                    pypi_0    pypi
> tornado                   6.1              py38h27cfd23_0    defaults
> tqdm                      4.62.1                   pypi_0    pypi
> traitlets                 5.1.1              pyhd3eb1b0_0    defaults
> transformers              4.18.0                   pypi_0    pypi
> typing-extensions         4.2.0                    pypi_0    pypi
> typing_extensions         4.1.1              pyh06a4308_0    defaults
> urllib3                   1.26.9                   pypi_0    pypi
> wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
> webencodings              0.5.1                    py38_1    defaults
> werkzeug                  2.1.2                    pypi_0    pypi
> wheel                     0.37.1             pyhd3eb1b0_0    defaults
> xz                        5.2.5                h7f8727e_1    defaults
> yacs                      0.1.8                    pypi_0    pypi
> yapf                      0.31.0                   pypi_0    pypi
> yarl                      1.7.2                    pypi_0    pypi
> zeromq                    4.3.4                h2531618_0    defaults
> zipp                      3.8.0            py38h06a4308_0    defaults
> zlib                      1.2.12               h7f8727e_2    defaults
> ```

**Based on the above, I installed the matching module and was able to run IgFold successfully**
```
 conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=11.0 -c pytorch
```

**Comment by anar-rzayev** [comment]
I am curious, how do you download the PyRosetta into your local? Do you run it from Ubuntu or other OS that supports PyRosetta?

**Comment by Licko0909** [comment]
> I am curious, how do you download the PyRosetta into your local? Do you run it from Ubuntu or other OS that supports PyRosetta?

PyRosetta acdemic license in Ubuntu
