### ISSUE TITLE
Chain breaks after Rosetta refinement

### ISSUE THREAD

**Issue by ta-rom** [Graylab/IgFold#52]
Hello!

Thank you for your great instrument.

I faced a problem with IgFold: sometimes Rosetta refinement creates breaks in the antibody chain.

A probable reason is that in the `pdb_string` of the predicted structure TER records are placed not at the end of the chain, but inside it (while they are in place after the `write_pdb_bfactor` function). I believe it is because `delims` list is [determined](https://github.com/Graylab/IgFold/blob/18a9c5892f2ccac21247959e6e2b487b053f3bbd/igfold/utils/folding.py#L103C1-L104C1) as containing the number of the last residue in the chain, but later atom number (k) and not residue number (r) is [searched](https://github.com/Graylab/IgFold/blob/18a9c5892f2ccac21247959e6e2b487b053f3bbd/igfold/utils/pdb.py#L465) in it.

**Comment by jeffreyruffolo** [comment]
Thanks for catching this! I believe I've now addressed the issue in a new release, `v0.3.3`. Please reopen if the issue persists though.
