### ISSUE TITLE
it seems a bug in save_PDB

### ISSUE THREAD

**Issue by zhendejuzi** [Graylab/IgFold#55]
![image](https://github.com/Graylab/IgFold/assets/5487444/d66dc04e-e7b6-46e1-9f46-dfefe3bfb33a)

Should delim be the number of atoms in the antibody backbone or the number of amino acids?

when I refine the pdb, the refined pdb's sequence will be change at the length of the VL and VH

**Comment by jeffreyruffolo** [comment]
Hi, thanks for pointing this out! I've now updated the PDB writing to properly place the terminal markers.
