### ISSUE TITLE
predict the structure using one single seq: H + linker + V

### ISSUE THREAD

**Issue by zhendejuzi** [Graylab/IgFold#56]
can I use a linker (for example, GGGGGGGGGGGGG) to connect the heavy chain and the light chain, and then use igfold for structure prediction?

**Comment by qiz218591** [comment]
Looking forward to the answer of the same doubt above?

**Comment by jeffreyruffolo** [comment]
This behavior is not technically supported, as the model is only trained on separate heavy and light chains. It might work though in some cases.
