### ISSUE TITLE
Corrupt structures

### ISSUE THREAD

**Issue by lhatsk** [Graylab/IgFold#61]
Hi,

I am currently testing IgFold on newer targets from SAbDab, for example, [7ox1 A/B](https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/sabdab/structureviewer/?pdb=7ox1) following the instructions in: https://github.com/Graylab/IgFold#antibody-structure-prediction-from-sequence using IgFold 0.4 (also tested 0.3.1).

For most of the targets, I end up with broken predictions, ie, no secondary structures and big clashes (see attachment). The example on GitHub works. Any idea what's going wrong?

Thanks!

`sequences = {'H': 'QLQLVESGPGLVKPSQTLSLTCTVSGGSITTGYYAWSWIRQPPGKGLEWMGFIARDGSTSYSPSLKSRTSISRDTSKNQFSLQLSSVTPEDTAVYYCARAGEGRSWYPGYYYGMDYWGKGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSC',
 'L': 'QAVVTQEPSLSVSPGGTVTLTCGLSSGSVTSSNYPGWYQQTPGQAPRVLIYNTNSRHSGVPSRYSGFISGNKAALTITGAEPEDEADYYCHLHKGSTGVFGGGTHLTVLSQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS'}`

![7ox1_igfold](https://github.com/Graylab/IgFold/assets/4652862/cbacadd7-82c4-4cab-9449-883eae429b5f)

**Comment by lhatsk** [comment]
I just noticed that the problem is caused by using the full heavy / light chain from the PDB.

**Comment by jeffreyruffolo** [comment]
Hi, yes that's correct. IgFold expects to receive just the Fv portions of the heavy and light chains.
