### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by johnsnowgo** [Graylab/IgFold#65]
Hi, I have installed igfold according to the following command: `git clone git@github.com:Graylab/IgFold.git `, `pip install IgFold`, `conda install -c conda-forge openmm==7.7.0 pdbfixer`, `conda install -c bioconda abnumber`. However,  ValueError was reported when I run the example given in the README.md.
```
from igfold import IgFoldRunner
from igfold.refine.pyrosetta_ref import init_pyrosetta

init_pyrosetta()

sequences = {
    "H": "EVQLVQSGPEVKKPGTSVKVSCKASGFTFMSSAVQWVRQARGQRLEWIGWIVIGSGNTNYAQKFQERVTITRDMSTSTAYMELSSLRSEDTAVYYCAAPYCSSISCNDGFDIWGQGTMVTVS",
    "L": "DVVMTQTPFSLPVSLGDQASISCRSSQSLVHSNGNTYLHWYLQKPGQSPKLLIYKVSNRFSGVPDRFSGSGSGTDFTLKISRVEAEDLGVYFCSQSTHVPYTFGGGTKLEIK"
}
pred_pdb = "my_antibody.pdb"

igfold = IgFoldRunner()
igfold.fold(
    pred_pdb, # Output PDB file
    sequences=sequences, # Antibody sequences
    do_refine=True, # Refine the antibody structure with PyRosetta
    do_renum=True, # Renumber predicted antibody structure (Chothia)
)
```

Error info was as following:
```
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "path_to_IgFold/igfold/IgFoldRunner.py", line 106, in fold
   model_out=fold(
 File "path_to_IgFold/igfold/utils/folding.py", line 219, in fold
   best_model_i = scores.index(min(scores))
ValueError: min() arg is an empty sequence
```

I saw the similar error were arose in [https://github.com/Graylab/IgFold/issues/31](url). But I can't solve this problem by run `pip install .`. 
Could you please help me to fix. THX.

**Comment by NooriFatima** [comment]
Facing the same issue. This occurs when there are no model checkpoints to load in. I've pip installed both IgFolds but the weights aren't being brought in through it. I'll update if I find a fix!

**Comment by NooriFatima** [comment]
I figured out the issue: if you put this python file outside of the git igfold (without the folder trained_models), the checkpoint file array is empty. If you put the file inside the igfold folder and have done pip install igfold, it'll import the checkpoint files from the pip install without getting confused about paths. I hope that helps!

**Comment by johnsnowgo** [comment]
> I figured out the issue: if you put this python file outside of the git igfold (without the folder trained_models), the checkpoint file array is empty. If you put the file inside the igfold folder and have done pip install igfold, it'll import the checkpoint files from the pip install without getting confused about paths. I hope that helps!

Can you describe how you solved it in more detail? Which python file needs to be moved after `git clone git@github.com:Graylab/IgFold.git` before executing `pip install IgFold`?

**Comment by NooriFatima** [comment]
> > I figured out the issue: if you put this python file outside of the git igfold (without the folder trained_models), the checkpoint file array is empty. If you put the file inside the igfold folder and have done pip install igfold, it'll import the checkpoint files from the pip install without getting confused about paths. I hope that helps!
> 
> Can you describe how you solved it in more detail? Which python file needs to be moved after `git clone git@github.com:Graylab/IgFold.git` before executing `pip install IgFold`?

So I made a file using the code in the README that takes in sequence and pred_pdb name, and was running it in of the `IgFold` directory that's generated by doing the git clone step. However, when the file runs `import igfold`, it brings in the `igfold` subdirectory in `IgFold/igfold` instead of importing the igfold folder installed in the python packages directory through the pip install step. The package directory has trained models pre-trained weights, the git clone directory does not. So I simply moved my file into the `IgFold/igfold` directory so it stopped importing the wrong path. Let me know if you have any further questions! Also, order of installation/moving the file doesn't matter here. Only file path.

**Comment by lalala0520** [comment]
> > > I figured out the issue: if you put this python file outside of the git igfold (without the folder trained_models), the checkpoint file array is empty. If you put the file inside the igfold folder and have done pip install igfold, it'll import the checkpoint files from the pip install without getting confused about paths. I hope that helps!
> > 
> > 
> > Can you describe how you solved it in more detail? Which python file needs to be moved after `git clone git@github.com:Graylab/IgFold.git` before executing `pip install IgFold`?
> 
> So I made a file using the code in the README that takes in sequence and pred_pdb name, and was running it in of the `IgFold` directory that's generated by doing the git clone step. However, when the file runs `import igfold`, it brings in the `igfold` subdirectory in `IgFold/igfold` instead of importing the igfold folder installed in the python packages directory through the pip install step. The package directory has trained models pre-trained weights, the git clone directory does not. So I simply moved my file into the `IgFold/igfold` directory so it stopped importing the wrong path. Let me know if you have any further questions! Also, order of installation/moving the file doesn't matter here. Only file path.

I have the same issue. I have followed the steps you described above, but unfortunately, I saw the same issue again. Could you give a snapshot of your files in igfold directory? I don't have the folder trained_models in the folder igfold as you mentioned. Thanks!

**Comment by lalala0520** [comment]
> > > > I figured out the issue: if you put this python file outside of the git igfold (without the folder trained_models), the checkpoint file array is empty. If you put the file inside the igfold folder and have done pip install igfold, it'll import the checkpoint files from the pip install without getting confused about paths. I hope that helps!
> > > 
> > > 
> > > Can you describe how you solved it in more detail? Which python file needs to be moved after `git clone git@github.com:Graylab/IgFold.git` before executing `pip install IgFold`?
> > 
> > 
> > So I made a file using the code in the README that takes in sequence and pred_pdb name, and was running it in of the `IgFold` directory that's generated by doing the git clone step. However, when the file runs `import igfold`, it brings in the `igfold` subdirectory in `IgFold/igfold` instead of importing the igfold folder installed in the python packages directory through the pip install step. The package directory has trained models pre-trained weights, the git clone directory does not. So I simply moved my file into the `IgFold/igfold` directory so it stopped importing the wrong path. Let me know if you have any further questions! Also, order of installation/moving the file doesn't matter here. Only file path.
> 
> I have the same issue. I have followed the steps you described above, but unfortunately, I saw the same issue again. Could you give a snapshot of your files in igfold directory? I don't have the folder trained_models in the folder igfold as you mentioned. Thanks!

I figured out the issue by my way. In my case, I found that the folder trained_models didn't exist in `IgFold/igfold` directory that's generated by doing the git clone step, but it exist in `conda_path/envs/IgFold/lib/python3.8/site-packages/igfold/` directory. I just created a soft link of 'trained_models' on `IgFold/igfold` directory that's generated by 'git clone', and the prediction was outputted successfully. I hope that helps!

**Comment by johnsnowgo** [comment]
Here I conclude the solution. `git clone git@github.com:Graylab/IgFold.git`, `pip install igfold`, move or copy `conda_path_to_IgFold_envs/lib/python3.xx/site-packages/igfold/trained_models` directory into the `IgFold/igfold` directory you git clone. Then It works. Thanks everybody.

**Comment by yangly-simon** [comment]
> Here I conclude the solution. `git clone git@github.com:Graylab/IgFold.git`, `pip install igfold`, move or copy `conda_path_to_IgFold_envs/lib/python3.xx/site-packages/igfold/trained_models` directory into the `IgFold/igfold` directory you git clone. Then It works. Thanks everybody.

thanks your answer, I solved same problem
