### ISSUE TITLE
About antiberty

### ISSUE THREAD

**Issue by nnnwyn** [Graylab/IgFold#7]
This is an interesting work. I saw you used pretrained model, AntiBERTy to represent the protein sequence and this package had been installed by pip. But I didn't see where it is used in the code. Could you give me any idea?

**Comment by jeffreyruffolo** [comment]
I ended up including AntiBERTy within the pre-trained weights of IgFold to ensure proper AntiBERTy are inputted into IgFold, so it doesn't actually show up in the code explicitly. You can see the model being called here:
https://github.com/Graylab/IgFold/blob/c31ee2ece3d567c2efea07185850a263b628372b/igfold/model/IgFold.py#L141

In case you want to use AntiBERTy as a standalone, it is available on PyPI as you mentioned. The documentation needs more detail, but after loading the model it should behave like a standard HuggingFace BERT model. 
https://pypi.org/project/antiberty/

**Comment by nnnwyn** [comment]
Okay，I see. Thanks so much. Very helpful answer!

**Comment by BartoszJanuszNA** [comment]
> I ended up including AntiBERTy within the pre-trained weights of IgFold to ensure proper AntiBERTy are inputted into IgFold, so it doesn't actually show up in the code explicitly. You can see the model being called here:
> 
> https://github.com/Graylab/IgFold/blob/c31ee2ece3d567c2efea07185850a263b628372b/igfold/model/IgFold.py#L141
> 
> In case you want to use AntiBERTy as a standalone, it is available on PyPI as you mentioned. The documentation needs more detail, but after loading the model it should behave like a standard HuggingFace BERT model. https://pypi.org/project/antiberty/

That standalone AntiBERTy package lacks tokenizer, I assume I can create my own using `resources/vocab.txt` from IgFold repo?

**Comment by jeffreyruffolo** [comment]
Hello, yes that is correct. AntiBERTy uses the `BertTokenizer` from HuggingFace with that vocab file.

**Comment by BartoszJanuszNA** [comment]
Thank you for quick response!
